environment:
  global:
    CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev"
  - "conda config --set always_yes True"
  - "conda info"
  - "conda env update -f environment.yml -n earthml"
  - "conda env update -f environment-dev.yml -n earthml"
  - "activate earthml"
  - "doit env_capture"

build: off
skip_branch_with_pr: true
clone_depth: 5
skip_tags: true

test_script:
  - "doit test_all"
